version: "3"
services: 
  postgres: 
    image: "postgres:15rc2-alpine3.16"
    container_name: "java-postgres"
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=GHTelegramActivityBot
    ports: 
      - "5432:5432"
  app: 
    build: ./
    container_name: "java-github-bot"
    ports: 
      - "8080:8080"